### ISSUE TITLE
clock() 함수 사용 시 영원히 잠드는 문제

### ISSUE THREAD

**Issue by redundant4u** [redundant4u/nemonemo_embedded_term#11]
**문제:**
c언어 환경에서 delay() 함수 구현을 위해 <time.h> 헤더의 ```clock()``` 함수를 통해 구현하였으나 보드가 동작 안 하는 문제 발생.

**원인:**

**해결:**
임시적으로 ```for()``` 문으로 처리.

https://github.com/redundant4u/nemonemo_embedded_term/blob/refactoring/user/bgm.c#L26

**Comment by goo-gy** [comment]
뭐야 커밋링크는 어케해

**Comment by redundant4u** [comment]
SysTick timer interrupt로 해결

https://github.com/redundant4u/nemonemo_embedded_term/commit/616e21fb007b16033e9e0cb085759708e1ff4f2d#diff-6e83c531f7f1e338fc3e946a72a4cd5195e3a59ad7d78702ff12ee5989c6bf81R6
