### ISSUE TITLE
뒤로가기 버튼

### ISSUE THREAD

**Issue by goo-gy** [redundant4u/nemonemo_embedded_term#4]
- pageScreen에 뒤로가기 버튼 필요

**Comment by goo-gy** [comment]
뒤로가기 버튼을 화면에 추가하지 말고
S2 버튼을 추가해서 취소(뒤로가기) 느낌으로 사용할까요?

**Comment by redundant4u** [comment]
seol 브랜치에 뒤로가기 기능 추가

추후 머지하면 close 예정

https://github.com/redundant4u/nemonemo_embedded_term/blob/seol/user/util.c#L13

**Comment by redundant4u** [comment]
[PR#10](https://github.com/redundant4u/nemonemo_embedded_term/pull/10)를 통해 구현 완료
